### ISSUE TITLE
Increase notification Timeout

### ISSUE THREAD

**Issue by ssc327** [engrbm87/notifications_android_tv#24]
I am trying to send a notification that includes a camera snapshot. The snapshot appears on my TV but my service call times out and reports an error after 5 seconds. Is it possible to increase the timeout or make it a variable? 
Alternatively should I explore having the request reply more quickly? If so, does that mean I need to shrink the payload/image?

https://github.com/engrbm87/notifications_android_tv/blob/549f5bf60beb70fd5bbcea828ca92c8f1671b266/notifications_android_tv/__init__.py#L188

**Comment by engrbm87** [comment]
Considering that the communication is happening in the local network taking more than 5 seconds is not considered normal. I suggest you check the snapshot size, if it's big check if you can have something with a smaller resolution.

**Comment by ssc327** [comment]
Thanks, I figured as much and tried to get that info but was not able to get the file size. I am using camera.snapshot but don't see a way to set the resolution and I also could not find it from the camera config.

Would upping the timeout increase the risk of resource exhaustion?

**Comment by engrbm87** [comment]
Changed to 10 seconds in latest release
